version: "3.3"

name: my_wallet

networks:
  my_wallet:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: mw_nginx
    ports:
      - '8080:80'
    volumes:
      - "../src:/var/www/html"
      - "./configs/nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - my_wallet

  app:
    build: 
      context: ../src
      dockerfile: Dockerfile
    container_name: mw_app
    ports:
      - "9000:9000"
    volumes:
      - "../src:/var/www/html:rw"
      - /var/www/html/vendor
    networks:
      - my_wallet

  mysql:
    image: mysql:latest
    container_name: mw_mysql
    ports:
      - "3306:3306"
    volumes:
      - "./mysql-data:/var/lib/mysql"
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - my_wallet

  phpmyadmin:
    image: phpmyadmin
    container_name: mw_phpmyadmin
    depends_on:
      - mysql
    restart: always
    tty: true
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
    volumes:
      - ./configs/pma.ini:/usr/local/etc/php/php.ini
    ports:
     - "8081:80"
    networks:
      - my_wallet
  
  redis:
    image: redis:alpine
    container_name: mw_redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - "./redis-data:/data"
    networks:
      - my_wallet

